### PR TITLE
break all the things

### PR DESCRIPTION
**Pull request by fqlx**

### CODE REVIEW

**Comment by DragonFire168** [comment]
At the point that I attempted the merge, it is not working beyond the point of displaying what is in the database. It doesn't do updates. At this point I'm going to keep the merged changes in a separate [branch](/DragonFire168/eZadvising/tree/juryben-master). When you submit a pull request, the features included in it should be in a **working** state.

**Comment by DragonFire168** [comment]
Also I will be using composer which is why the file was there, also the files in the .idea folder were version controlled for a reason. Please be more careful about which files you remove.

**Comment by fqlx** [comment]
why would you version control the .idea folder

**Comment by fqlx** [comment]
what are you taking about it doesnt do updates?  how does the user do an update?

**Comment by DragonFire168** [comment]
It doesn't update the database when the user moves a plan item, at least in my tests. It also appears to include incomplete functionality for different plans. I still have your changes in a separate branch, so I can plan the eventual merge, but I'll need it in a state where everything works before I can merge it into my master.

Certain files in the idea folder make sense to version control as they track how certain folders are marked (source, tests, resources, ect.), how they map to a development server, or what tabs are open. They work a lot better when version controlled because they can track state for different branches, for instance, accounting for files that are in one branch but not another. Every file that was in the .idea folder and version controlled was done on purpose.

**Pull request closed without merging**
